apiVersion: v1
kind: Namespace
metadata:
  name: sentiment-analysis
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-inference-cronjob
  namespace: sentiment-analysis
spec:
  schedule: "0 0 * * *"  # Runs every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: minikube-mount
            hostPath:
              path: /home/docker/hostvolume
              type: Directory
          containers:
          - name: batch-runner
            image: whitewolfie/batch-runner:latest
            imagePullPolicy: Always
            volumeMounts:
              - name: minikube-mount
                mountPath: /mnt/minikube
            resources:
              requests:
                cpu: 14
                memory: "12000000Ki"
          restartPolicy: OnFailure

