apiVersion: v1
kind: Namespace
metadata:
  name: sentiment-analysis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-api
  namespace: sentiment-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analysis-api
  template:
    metadata:
      labels:
        app: sentiment-analysis-api
    spec:
      containers:
      - name: sentiment-analysis-api
        image: whitewolfie/sentiment-analysis-inference:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  namespace: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
